name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup_deploy:
    name: "Preparar entorno de trabajo y desplegar"
    runs-on: ubuntu-22.04

    steps:
      - name: "Checkout del repositorio"
        uses: actions/checkout@v4

      - name: "Configurar Python 3.9"
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: "Instalar dependencias"
        run: |
          python -m pip install --upgrade pip
          pip install boto3 Flask pytest awscli
      - name: "Configurar credenciales AWS"
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: "us-east-1"

      - name: "Desplegar aplicación en AWS EC2"
        id: deploy_app
        run: |
          python src/deployment.py | tee deployment_output.txt
          LB_URL=$(grep -oP 'http://\S+' deployment_output.txt | tail -n 1)
          if [ -z "$LB_URL" ]; then
            echo "Error: No se encontró la URL de despliegue. Revisa deployment.py"
            exit 1
          fi
          echo "LB_URL=$LB_URL"
          echo "::set-output name=lb_url::$LB_URL"
        shell: bash

    outputs:
      lb_url: ${{ steps.deploy_app.outputs.lb_url }}

  performance:
    name: "Pruebas de rendimiento"
    runs-on: ubuntu-22.04
    needs: setup_deploy

    steps:
      - name: "Esperando 2 minutos a terminar de desplegar la infraestructura AWS..."
        run: sleep 120

      - name: "Clonar repositorio"
        uses: actions/checkout@v4

      - name: "Configurar Locust para pruebas de carga"
        env:
          LB_URL: ${{ needs.setup_deploy.outputs.lb_url }}
        run: |
          pip install locust
          echo "Prueba de carga en: $LB_URL"
          locust -f src/locustfile.py --headless -u 100 -r 10 -t 1m --host $LB_URL --html locust_result.html
          if [ ! -f "locust_result.html" ]; then
            echo "Error: El archivo locust_result.html no se generó correctamente."
            exit 1
          fi

      - name: "Subir resultados de rendimiento a S3"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        run: |
          aws s3 ls "s3://performance-reports-bucket" || aws s3 mb s3://performance-reports-bucket --region us-east-1
          echo "Subiendo resultados de Locust al bucket de S3..."
          aws s3 cp locust_result.html s3://performance-reports-bucket/locust_result.html
          echo "Resultados subidos exitosamente a S3."
